---
- hosts: all # ubuntu-devbox
  sudo: true
  gather_facts: false
  user: vagrant # (use default: vagrant) 
  sudo_user: root  # (use default: root)
  vars:
    host_name: ubuntu-vagrant-devbox
    user: vagrant
    git_username: Creative_Dev  # update
    git_email: your@bitbucket.acc  # update
  tasks:
    - name: download boulanger
      git: 
        repo=git@bitbucket.org:trapeze/boulanger.git dest=/home/{{ user }}/projects/boulanger
        accept_hostkey=yes
        update=yes
      sudo: false
    - name: retrieve the ssh keys in dir
      shell: cp -r /host_ssh/id* /home/vagrant/.ssh/
      sudo: false
    #   register: cert_files
    #- name: copy ssh keys to the devbox
    #  copy: src={{ item }} dest=/home/vagrant/.ssh/ owner={{ user }} group={{ user }} mode=644 
    #  with_items: cert_files.stdout_lines
    #  # same as with_items: home_dirs.stdout.split()
    #- command: pip --no-input install git+ssh://git@bitbucket.org/trapeze/boulanger.git#egg=boulanger
    - name: allow host forwarding
      template:
        src=templates/ssh_config.j2
        dest=/home/{{ user }}/.ssh/config
    #- name: change ssh folder permissions
    #  file: path=/home/vagrant/.ssh owner={{ user }} group={{ user }} state=directory recurse=yes
    # does not work, hangs ...
    #  pip: name=git+ssh://git@bitbucket.org/trapeze/boulanger.git#egg=boulanger
    - name: add node.js repo to /etc/apt-/sources.list/
      apt_repository: repo=ppa:chris-lea/node.js
      run_once: true
    - name: add ubuntugis repo to /etc/apt/sources.list/
      apt_repository: repo=ppa:ubuntugis/ubuntugis-unstable
      run_once: true
    - name: add git repo to /etc/apt/sources.list/
      apt_repository: repo=ppa:git-core/ppa
      run_once: true
    - name: update apt
      apt: update_cache=yes
    - apt: upgrade=safe
    - name: install image libraries
      apt: name={{ item }} state=present
      with_items:
        - libjpeg-dev
        - zlib1g-dev
        - libfreetype6-dev
      run_once: true
    - name: install required python
      apt: name={{ item }} state=present
      with_items:
        - python-pip 
        - python-dev 
        - build-essential
        - python-setuptools
        - openssh-server
        - python-imaging
        - ipython
        - python-docutils
        - python-software-properties
        - python-mapscript
        - python-crypto
        - bash-completion
      run_once: true
    - name: install avahi, exim, git, subversion, nginx, nodejs, vim, gettext
      apt: name={{ item }} state=present
      with_items:
        - avahi-daemon
        - exim4
        - git-core
        - git-svn
        - subversion
        - vim
        - nodejs
        - gettext
      run_once: true
    - name: install npm packages
      npm: name={{ item }} global=yes
      with_items:
        - grunt
        - grunt-cli
        - bower
        - grunt-init
      run_once: true
    - name: install postgres postgis
      apt: name={{ item }} state=present
      with_items:
        - postgresql-client-common
        - postgresql
        - postgis 
        - python-psycopg2
        - python-gdal
        - libproj-dev
        - gdal-bin
        - libpq-dev 
        - postgresql-9.3-postgis-scripts
      run_once: true
    - name: start postgres and enable at boot
      service: name=postgresql
               enabled=yes
               state=started      
      run_once: true
    - name: install unattended upgrades package
      apt: name=unattended-upgrades
      notify:
        - dpkg reconfigue unattended
      run_once: true
    - pip: name=setuptools
    - pip: name=pip version=6.0.6
    - pip: name=Pillow
    - pip: name=fabric
    - pip: name=gunicorn
    - pip: name=fogbugz
    - pip: name=BeautifulSoup
    - name: create locale, ensure exists
      locale_gen: name=en_CA.UTF-8 state=present
    - command: update-locale LANG=en_CA.UTF-8 # usr/sbin
    - name: update hostname
      hostname: name={{ host_name }}
    - name: create gitconfig
      sudo: false
      template: 
        src=templates/gitconfig.j2
        dest=/home/{{ user }}/.gitconfig
    - name: set timezone variables
      copy: content='America/Toronto'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      ignore_errors: yes
      notify:
        - update timezone
      run_once: true
    - name: update bashrc PYTHONPATH
      lineinfile:
        dest=/home/{{ user }}/.bashrc
        line="export PYTHONPATH=.:..:../lib"
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
    - name: dpkg reconfigure
      command: >
        dpkg-reconfigure unattended
        --frontend noninteractive
        -plow unattended-upgrades
    - name: restart postgresql
      service: name=postgresql state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
    - name: update exim4.conf
      shell: /usr/sbin/update-exim4.conf
